In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters

In [10]:
import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, AGE, RANK AS COMPETITION_RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, DATE
FROM `saa-analytics.results.saa_full` 
WHERE RESULT!='NM' AND RESULT!='FOUL' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT IS NOT NULL AND (CATEGORY_EVENT='Sprint' OR CATEGORY_EVENT='Mid' OR CATEGORY_EVENT='Hurdles' OR CATEGORY_EVENT='Relay' OR CATEGORY_EVENT='Walk' OR CATEGORY_EVENT='Marathon' OR CATEGORY_EVENT='Steeple')
"""

athletes = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [6]:
athletes

,NAME,RESULT,AGE,COMPETITION_RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,DATE
0,Supanich Poolkerd,11.63,None,1,100m,Sprint,Female,SEA Games,None
1,Kristina Knott,11.66,None,2,100m,Sprint,Female,SEA Games,None
2,Zaidatul Husniah Zulkifli,11.69,None,3,100m,Sprint,Female,SEA Games,None
3,Hoang Du Y,11.73,None,4,100m,Sprint,Female,SEA Games,None
4,Elizabeth-Ann Tan Shee Ru,12.0,None,5,100m,Sprint,Female,SEA Games,None
...,...,...,...,...,...,...,...,...,...
16317,"Aw, Hailey",37.68,11,28,Girls 11-12 200 Meter Dash U13,Sprint,Female,10th Club ZOOM Kindred Spirit Series 2023,2023
16318,"Wang, Minqi",29.97,12,4,Girls 11-12 200 Meter Dash U13,Sprint,Female,10th Club ZOOM Kindred Spirit Series 2023,2023
16319,"Koh, Jayna Jia Y",33.03,12,19,Girls 11-12 200 Meter Dash U13,Sprint,Female,10th Club ZOOM Kindred Spirit Series 2023,2023
16320,"Mak, Chen Yu, Adelyn",34.73,11,25,Girls 11-12 200 Meter Dash U13,Sprint,Female,10th Club ZOOM Kindred Spirit Series 2023,2023
16321,"Ong, Bella",37.80,9,29,Girls 11-12 200 Meter Dash U13,Sprint,Female,10th Club ZOOM Kindred Spirit Series 2023,2023

In [13]:
credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT NAME, RESULT, RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, STAGE
FROM `saa-analytics.results.saa_full`
WHERE STAGE='Final' AND COMPETITION='SEA Games' AND RANK='3' AND (CATEGORY_EVENT='Sprint' OR CATEGORY_EVENT='Mid' OR CATEGORY_EVENT='Hurdles' OR CATEGORY_EVENT='Relay' OR CATEGORY_EVENT='Walk' OR CATEGORY_EVENT='Marathon' OR CATEGORY_EVENT='Steeple')
"""

benchmarks = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [14]:
benchmarks

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE
0,Trần Thị Nhi Yến,11.75,3,100m,Sprint,Female,SEA Games,Final
1,Zaidatul Husniah Zulkifli,23.6,3,200m,Sprint,Female,SEA Games,Final
2,Nguyễn Thị Hằng,53.84,3,400m,Sprint,Female,SEA Games,Final
3,Goh Chui Ling,2:09.15,3,800m,Mid,Female,SEA Games,Final
4,Goh Chui Ling,4:26.33,3,1500m,Mid,Female,SEA Games,Final
5,Odekta Elvina Naibaho,35:31.03,3,10000m,Sprint,Female,SEA Games,Final
6,Dina Aulia,13.59,3,100m hurdles,Hurdles,Female,SEA Games,Final
7,Nguyễn Thị Ngọc,59.09,3,400m hurdles,Hurdles,Female,SEA Games,Final
8,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final
9,"Azreen Nabila Alias, Nur Afrina Batrisyia, N...",44.58,3,4 x 100m relay,Relay,Female,SEA Games,Final
10,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final
11,Christine Organiza Hallasgo,2:50:27,3,Marathon,Marathon,Female,SEA Games,Final
12,Kotchaphon Tangsrivong,1:57:11,3,20km race walk,Walk,Female,SEA Games,Final
13,Muhammad Haiqal Hanafi,10.443,3,100m,Sprint,Male,SEA Games,Final
14,Lalu Muhammad Zohri,21.02,3,200m,Sprint,Male,SEA Games,Final
15,Frederick Ramirez,46.63,3,400m,Sprint,Male,SEA Games,Final
16,Wan Muhammad Fazri Wan Zahari,1:53.86,3,800m,Mid,Male,SEA Games,Final
17,Tan Htike Soe,31:25.55,3,10000m,Sprint,Male,SEA Games,Final
18,John Cabang,13.855,3,110m hurdles,Hurdles,Male,SEA Games,Final
19,Calvin Quek,50.75,3,400m hurdles,Hurdles,Male,SEA Games,Final
20,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final
21,"Jonathan Nyepa, Khairul Hafiz Jantan, Mohama...",39.36,3,4 x 100m relay,Relay,Male,SEA Games,Final
22,"Muhammad Firdaus Zemi, Ruslem Zikry Putra Ro...",3:08.82,3,4 x 400m relay,Relay,Male,SEA Games,Final
23,Nguyen Thanh Hoang,2:35:49,3,Marathon,Marathon,Male,SEA Games,Final
24,Pyae Phyo Htun,1:49:39,3,20km race walk,Walk,Male,SEA Games,Final